export const lancheDaManhaOptions = [
  { id: "maca", nome: "Maçã", foodId: 221, emoji: "🍎", selected: false },
  { id: "banana", nome: "Banana", foodId: 182, emoji: "🍌", selected: false },
  { id: "laranja", nome: "Laranja", foodId: 212, emoji: "🍊", selected: false },
  { id: "abacaxi", nome: "Abacaxi", foodId: 164, emoji: "🍍", selected: false },
  { id: "mamao", nome: "Mamão", foodId: 226, emoji: "🍍", selected: false },
  { id: "morango", nome: "Morango", foodId: 239, emoji: "🍓", selected: false },
  {
    id: "melancia",
    nome: "Melancia",
    foodId: 235,
    emoji: "🍉",
    selected: false,
  },
  { id: "melao", nome: "Melão", foodId: 236, emoji: "🍈", selected: false },
  { id: "kiwi", nome: "Kiwi", foodId: 207, emoji: "🥝", selected: false },
  {
    id: "whey_protein",
    nome: "Whey Protein",
    foodId: 614,
    emoji: "🥛",
    selected: false,
  },
  {
    id: "biscoito_polvilho",
    nome: "Biscoito de Polvilho",
    foodId: 615,
    emoji: "🍪",
    selected: false,
  },
  {
    id: "biscoito_agua_sal",
    nome: "Biscoito de Agua e Sal",
    foodId: 616,
    emoji: "🍪",
    selected: false,
  },
  {
    id: "biscoito_arroz",
    nome: "Biscoito de Arroz",
    foodId: 617,
    emoji: "🍪",
    selected: false,
  },
];
