export const cafeDaManhaOptions = {
  breakfast: [
    {
      id: "pao_frango",
      nome: "Pão com Frango",
      foodId: [50, 600],
      emoji: "🥖",
      selected: false,
    },
    {
      id: "pao_ovo",
      nome: "Pão com Ovo",
      foodId: [53, 490],
      emoji: "🍳",
      selected: false,
    },
    {
      id: "pao_queijo_fatia",
      nome: "Pão com Queijo",
      foodId: [50, 467],
      emoji: "🧀",
      selected: false,
    },
    {
      id: "pao_presunto_queijo",
      nome: "Pão com Presunto e Queijo",
      foodId: [50, 438, 467],
      emoji: "🥪",
      selected: false,
    },
    {
      id: "pao_peru_queijo",
      nome: "Pão com Peito de Peru e Queijo",
      foodId: [50, 618, 467],
      emoji: "🥪",
      selected: false,
    },
    {
      id: "tapioca_queijo",
      nome: "Tapioca de Queijo",
      foodId: [551, 467],
      emoji: "🌮",
      selected: false,
    },
    {
      id: "tapioca_frango",
      nome: "Tapioca de Frango",
      foodId: [551, 600],
      emoji: "🌮",
      selected: false,
    },
    {
      id: "cuscuz_frango",
      nome: "Cuscuz com Frango",
      foodId: [533, 600],
      emoji: "🌽",
      selected: false,
    },
    {
      id: "pao_queijo",
      nome: "Pão de Queijo",
      foodId: [140],
      emoji: "🧀",
      selected: false,
    },
    {
      id: "omelete",
      nome: "Omelete",
      foodId: [602],
      emoji: "🍳",
      selected: false,
    },
  ],
  fruits: [
    { id: "maca", nome: "Maçã", foodId: 221, emoji: "🍎", selected: false },
    { id: "banana", nome: "Banana", foodId: 182, emoji: "🍌", selected: false },
    {
      id: "laranja",
      nome: "Laranja",
      foodId: 212,
      emoji: "🍊",
      selected: false,
    },
    {
      id: "abacaxi",
      nome: "Abacaxi",
      foodId: 164,
      emoji: "🍍",
      selected: false,
    },
    { id: "mamao", nome: "Mamão", foodId: 226, emoji: "🍍", selected: false },
    {
      id: "morango",
      nome: "Morango",
      foodId: 239,
      emoji: "🍓",
      selected: false,
    },
    {
      id: "melancia",
      nome: "Melancia",
      foodId: 235,
      emoji: "🍉",
      selected: false,
    },
    { id: "melao", nome: "Melão", foodId: 236, emoji: "🍈", selected: false },
    { id: "kiwi", nome: "Kiwi", foodId: 207, emoji: "🥝", selected: false },
  ],
  liquids: [
    {
      id: "cafe_leite",
      nome: "Café com Leite Desnatado",
      foodId: 613,
      emoji: "☕",
      selected: false,
    },
    { id: "cafe", nome: "Café", foodId: 511, emoji: "☕", selected: false },
    {
      id: "iogurte",
      nome: "Iogurte",
      foodId: 448,
      emoji: "🥛",
      selected: false,
    },
    {
      id: "suco_laranja",
      nome: "Suco de Laranja",
      foodId: 209,
      emoji: "🧃",
      selected: false,
    },
    {
      id: "suco_limao",
      nome: "Suco de Limão",
      foodId: 218,
      emoji: "🧃",
      selected: false,
    },
    {
      id: "suco_uva",
      nome: "Suco de Uva",
      foodId: 258,
      emoji: "🧃",
      selected: false,
    },
  ],
};

export type CafeDaManhaOptions = typeof cafeDaManhaOptions;
